### ISSUE TITLE
This no longer works on macOS High Sierra

### ISSUE THREAD

**Issue by finferflu** [alberti42/iTunes-Volume-Control#11]
It did work up to macOS Sierra, though.

**Comment by PUncle** [comment]
Its a sad day :(

**Comment by finferflu** [comment]
I’ll try to reinstall it, maybe that does the trick...

**Comment by finferflu** [comment]
OK, reinstalling it kind of worked. Eventually it stops working again, and I need to quit it and restart it. So I'd say there's still some sort of bug that needs addressing.

**Comment by F3000** [comment]
Working fine on 10.13.3

**Comment by ahmetcetin** [comment]
doesn't work on mojave

**Comment by alberti42** [comment]
Dear Ahmet,

Have a look. I have uploaded a new version compatible with Mojave.

Best, Andrea

**Comment by ahmetcetin** [comment]
Hi Andrea,
I installed this version but when I run, it just doesn't work at all, it doesn't appear in menu bar, nothing.

**Comment by alberti42** [comment]
Dear Ahmet,

Thank you for your feedback. It seems that there are more restrictions imposed by Mojave about distributing applications outside of the App store; see https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution <https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution>. I should do some further investigation. 

Two questions:

- Are you running Mojave?
- Have you checked the Security & Privacy setting (see also explanation at https://github.com/alberti42/iTunes-Volume-Control/blob/master/README.md)? You could try to remove it and insert it again.
- Is there any error displayed?

**Comment by alberti42** [comment]
I added further instructions on the readme page how the app can be installed on Mojave disable the Gatekeeper protection. This might solve the problem, hopefully.

**Comment by alberti42** [comment]
I have upgraded to 1.6.0. If you still have the old version installed, it should be simply possible to update to the newest version automatically from the application itself. Best, Andrea

**Comment by alberti42** [comment]
Mojave is now supported. Prior version to Mojave are no longer supported.
