### ISSUE TITLE
1.5.2 crashes immediately

### ISSUE THREAD

**Issue by jconley** [alberti42/iTunes-Volume-Control#13]
console logs:
```
default	13:19:44.525178 -0500	amfid	/Applications/iTunes Volume Control.app/Contents/MacOS/iTunes Volume Control signature not valid: -2147409652
default	13:19:44.546383 -0500	kernel	proc 81209: load code signature error 4 for file "iTunes Volume Control"
```
mojave 10.14.5

**Comment by alberti42** [comment]
Dear Johnathan,

While I was updating iTunes Volume Control to version 1.5.3, I made a mistake so that the signature was not valid. Would you like to try it again to update the app to the latest version? The new version 1.5.3 improves on the visualization of the volume bar.

Best, Andrea

**Comment by jconley** [comment]
i still have the same issue with 1.5.3
here is some additional information from the .crash report:
```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

**Comment by alberti42** [comment]
Dear Jonathan,

Thank you for your quick feedback. I would like to fix your problem. Tomorrow I will have the app tested on some other computer, and on a different account than my own. My tests on two computers of mine have worked fine so far.

Best, Andrea

**Comment by alberti42** [comment]
I could reproduce your error. The problem is explained here http://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/ <http://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/>

There is however no problem if you download from command line. From terminal, type:

wget https://github.com/alberti42/iTunes-Volume-Control/raw/master/iTunes%20Volume%20Control.dmg <https://github.com/alberti42/iTunes-Volume-Control/raw/master/iTunes%20Volume%20Control.dmg>

Then you can open it with Finder and copy the program in the /Applications/ folder.

The other possibility is that you type from terminal 

xattr -cr ~/Desktop/iTunes\ Volume\ Control.app/

as suggested in the online article I linked above. This command removes some extended attributes which are added by the browser (Safari etc) when downloading. In the next days I will have to figure out how to avoid this cumbersome procedure. I would be grateful if you can confirm to me that this procedure solves problem.

Best, Andrea

**Comment by alberti42** [comment]
I have added an explanation also on the readme page in Github https://github.com/alberti42/iTunes-Volume-Control <https://github.com/alberti42/iTunes-Volume-Control> how to avoid the quarantine flag. This is probably some defense mechanism of MacOS. Maybe the only alternative would be to put the application on the App store and charge some little price for it. I hope that this will not be necessary.

Best,
Andrea

**Comment by alberti42** [comment]
It now seems to work after I also signed the dmg package. Let me know.

**Comment by jconley** [comment]
i'm not sure this is the same issue... i do not get the "damaged application" error message... i get no messages at all.  i only see error messages in the Console.app.  i originally installed/upgraded the app using `brew cask install itunes-volume-control` which uses curl to download on the command line.
i also tried downloading the .dmg you provided (vs the .zip on your website) from the terminal... but got the same results.
i tried the xattr suggestion, but it did not help.

i'm not sure if this applies, but i did find this regarding mojave 10.14.5:
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by marcstein** [comment]
Hi Andrea,

The app worked great until last week when it ceased. I've tried all the posted suggestions, command line download, quarantine step... But no luck. Attached is the crash report in the hope that it might be useful to you.
[iTunes Volume Control_2019-06-05-104900_Marcs-Mac-Pro.crash.txt](https://github.com/alberti42/iTunes-Volume-Control/files/3257747/iTunes.Volume.Control_2019-06-05-104900_Marcs-Mac-Pro.crash.txt)

Running 10.14.5

Thanks for the app!

Best,

Marc

**Comment by jconley** [comment]
the latest rebuild of 1.6.0 seems to have resolved the issue.
i did have to remove the old Privacy/Accessibility permission and let the app re-request it.

**Comment by alberti42** [comment]
Dear Marc,

I have upgraded the software (Sparkle) taking care of updates. I have fixed a bug in that software and fixed a mistake I was doing when creating the zip file used for the automatic upgrades. One mistake is that I was not preserving symbolic links.

So, after fixing several problems, I think it is worth trying the latest rebuild of 1.6.0. You can either download the DMG file or run an old copy of the app and click on update. In any case, you should delete the old permission (see also this screenshot <https://camo.githubusercontent.com/3154f6a2d68f0183ea3eff4388c6b429bf96efd8/68747470733a2f2f7261772e6769746875622e636f6d2f616c626572746934322f6954756e65732d566f6c756d652d436f6e74726f6c2f6d61737465722f5365637572697479507269766163792e706e67>) before running the new version. It will ask you to authorize the app once again.

Best, Andrea

**Comment by marcstein** [comment]
Hi Andrea,

Outstanding! It's working great again.

Thanks so much for this incredibly useful app!

Best,

Marc


Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. marc.stein@underwrite.ai
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>
