### ISSUE TITLE
Support for controlling Spotify Connect speakers

### ISSUE THREAD

**Issue by holleboom** [alberti42/iTunes-Volume-Control#15]
It only controls volume when playing locally through the macbook speakers, but it doesn't control the volume when playing through Spotify Connect speakers.

**Comment by holleboom** [comment]
Yes I'm running the latest version. It doesn't move the volume rocker when playing over the external speakers. It doest work when playing locally:


![CleanShot 2019-06-21 at 12 39 48](https://user-images.githubusercontent.com/1815053/59917223-b26f9700-9421-11e9-8530-0ebd96710239.gif)

**Comment by alberti42** [comment]
Thank you for the clip. You wrote "It doest work when playing locally" but the video shows the you can control the volume when playing on the local computer. However, I see that you cannot control Spotify Connect Speaker.

I have written a very short AppleScript that shows how to control Spotify's volume. It ramps up and down the volume as shown in the animated gif below. If you succeed to make it work with your Spotify Connect Speaker, I will be happy to include the modification in the app. The app uses similar technology (AppleEvents) as AppleScript to communicate with the music player.

![Spotify volume ramp](https://user-images.githubusercontent.com/61808/59935821-ef9e4e00-944e-11e9-81cc-075f7f48f2fd.gif)

[Spotify volume control.zip](https://github.com/alberti42/iTunes-Volume-Control/files/3315239/Spotify.volume.control.zip)

**Comment by holleboom** [comment]
Sorry, I meant It **does** work when playing locally :)

I tried getting it to work using your script, but I failed as I'm not an experienced.

However, I found something that might help. There is a Spotify Mini Player plugin for Alfred that supports controlling the volume of a Spotify Connect speaker. The below script (php)is used to achieve that, I think. Does that help?


````
/**
 * getVolumeSpotifyConnect function.
 *
 * @param mixed $w
 */
 function getVolumeSpotifyConnect($w, $device_id)
 {
    $retry = true;
    $nb_retry = 0;
    while ($retry) {
        try {
            $api = getSpotifyWebAPI($w);
            
            $devices = $api->getMyDevices();
            $retry = false;
            if(isset($devices->devices)) {
                foreach ($devices->devices as $device) {
                    if ($device->is_active) {
                        return $device->volume_percent;
                    }
                }
            }
            return false;
        } catch (SpotifyWebAPI\SpotifyWebAPIException $e) {
            logMsg('Error(getVolumeSpotifyConnect): retry '.$nb_retry.' (exception '.jTraceEx($e).')');
            if ($e->getCode() == 429) { // 429 is Too Many Requests
                $lastResponse = $api->getRequest()->getLastResponse();
                $retryAfter = $lastResponse['headers']['Retry-After'];
                sleep($retryAfter);
            } else if ($e->getCode() == 404) {
                // skip
                break;
            } else if (strpos(strtolower($e->getMessage()), 'ssl') !== false) {
                // cURL transport error: 35 LibreSSL SSL_connect: SSL_ERROR_SYSCALL error #251
                // https://github.com/vdesabou/alfred-spotify-mini-player/issues/251
                // retry any SSL error
                ++$nb_retry;
            } else if ($e->getCode() == 500
                || $e->getCode() == 502 || $e->getCode() == 503 || $e->getCode() == 202) {
                // retry
                if ($nb_retry > 2) {
                    handleSpotifyWebAPIException($w, $e);
                    $retry = false;

                    return false;
                }
                ++$nb_retry;
                sleep(5);
            } else {
                handleSpotifyWebAPIException($w, $e);
                $retry = false;

                return false;
            }
        }
    }
}

/**
 * changeVolumeSpotifyConnect function.
 *
 * @param mixed $w
 */
 function changeVolumeSpotifyConnect($w, $device_id, $volume_percent)
 {
    $retry = true;
    $nb_retry = 0;
    while ($retry) {
        try {
            $api = getSpotifyWebAPI($w);
            $api->changeVolume([
                'volume_percent' => $volume_percent,
            ]);
            $retry = false;
        } catch (SpotifyWebAPI\SpotifyWebAPIException $e) {
            logMsg('Error(changeVolumeSpotifyConnect): retry '.$nb_retry.' (exception '.jTraceEx($e).')');
            if ($e->getCode() == 429) { // 429 is Too Many Requests
                $lastResponse = $api->getRequest()->getLastResponse();
                $retryAfter = $lastResponse['headers']['Retry-After'];
                sleep($retryAfter);
            } else if ($e->getCode() == 404) {
                // skip
                break;
            } else if (strpos(strtolower($e->getMessage()), 'ssl') !== false) {
                // cURL transport error: 35 LibreSSL SSL_connect: SSL_ERROR_SYSCALL error #251
                // https://github.com/vdesabou/alfred-spotify-mini-player/issues/251
                // retry any SSL error
                ++$nb_retry;
            } else if ($e->getCode() == 500
                || $e->getCode() == 502 || $e->getCode() == 503 || $e->getCode() == 202) {
                // retry
                if ($nb_retry > 2) {
                    handleSpotifyWebAPIException($w, $e);
                    $retry = false;

                    return false;
                }
                ++$nb_retry;
                sleep(5);
            } else {
                handleSpotifyWebAPIException($w, $e);
                $retry = false;

                return false;
            }
        }
    }
 }
````

**Comment by HHR18** [comment]
Any updates on this? I'm loving the system-wide volume control but would love if it works with my Spotify Connect speakers as well :)

**Comment by alberti42** [comment]
I remember I spent a few hours trying to make it work. The challenge is to be able to write a small piece of code, in whichever language, that shows to me how you can control Spotify Connect speakers. I do not own these speakers myself.

To my present understanding, these speakers are controlled via an internet communication protocol, and not as a peripheral directly connected to the computer. Perhaps someone out there has better ideas.

**Comment by holleboom** [comment]
Good news, Spotify has finally fixed this missing feature or bug! So controlling volume of Spotify Connect  speakers is now possible out of the box using iTunes Volume Control.
