### ISSUE TITLE
Seems like not working with "music" in macOS 10.15 beta 

### ISSUE THREAD

**Issue by normanmaurer** [alberti42/iTunes-Volume-Control#17]
When using the music app which is the replacement of iTunes with macOS 10.15 beta the volume control does not work.

**Comment by alberti42** [comment]
That is correct, it does not work with the new Music app yet. I have installed the preview of Catalina in a virtual machine running with Parallels. However, there are still bugs that prevent me from using Xcode, necessary for the development, in Catalina, when using Parallels' virtual machine. Once this will be fixed, I am confident I will be able to produce a version compatible with Catalina. Can you wait until then?

**Comment by normanmaurer** [comment]
sure... Just wanted to report it and see if its a "known" issue :)

**Comment by w0lfschild** [comment]
Until the original dev is able to update the app here's a version I built for 10.15 which adjust the music apps volume:

[iTunes Volume Control.zip](https://github.com/alberti42/iTunes-Volume-Control/files/3587022/iTunes.Volume.Control.zip)

**Comment by MainasuK** [comment]
As far as I know. The Catalina Music.app bundle name changed to "com.apple.Music".  Also some of Podcast & Movie e.t.c script removed from Apple Script dictionary. But the Music part of the script dictionary is as same as iTunes.app. 

I write a bundle name helper and use like that:
`let application = SBApplication(bundleIdentifier: OSVersionHelper.bundleIdentifier)`

https://github.com/MainasuK/Song-Rating/blob/master/Song%20Rating/iTunes/OSVersionHelper.swift

**Comment by alberti42** [comment]
Thank you for your work! I am now on travel but once I am back I will take care of including your changes into the main branch.

**Comment by maxvoltar** [comment]
Subscribe.

**Comment by ErinPo** [comment]
> Thank you for your work! I am now on travel but once I am back I will take care of including your changes into the main branch.
> […](#)

Any chance you're back? Catalina final is out and the volume control is the same as in the beta... still requiring an adaptation.

**Comment by ErinPo** [comment]
> Until the original dev is able to update the app here's a version I built for 10.15 which adjust the music apps volume:
> 
> [iTunes Volume Control.zip](https://github.com/alberti42/iTunes-Volume-Control/files/3587022/iTunes.Volume.Control.zip)

Nice one, it worked for me, albeit without the visual distinction between system volume and music app volume that was previously there in the volume bar overlay animation.

**Comment by superjunky** [comment]
On the subject of the visual notification... I would like it to be high res so much! ;)

**Comment by alberti42** [comment]
The new version 1.6.7 fixes the compatibility issues with Catalina.

**Comment by superjunky** [comment]
For me it doesn't appear to do so. The beta did, but 1.6.7 does not change the volume of the music.app..

**Comment by alberti42** [comment]
Have you downloaded the official version 1.6.7? People reported that it worked for them. Have you correctly removed from the security setting the application, and then restarted it, so that it asks you again to be authorized?

This cannot be changed. It is (unfortunate) a feature of MacOS. Without an Apple code-signature (which would costs me about 100$ a year) I am afraid that you have to authorize the application every time it gets updated.

**Comment by superjunky** [comment]
Thanks for the reply Alberti. The next day I woke the pc, and it was working like expected! Perhaps something got stuck inbetween and solved itself.
Thanks again for this nice app :)
