### ISSUE TITLE
Icon transparent on startup

### ISSUE THREAD

**Issue by julianschmidl** [alberti42/iTunes-Volume-Control#22]
Hello,

I really like the tool and I like to provide a short feedback on a minor issue:
The icon appears to be transparent on startup. However it's visible again after the UI switched to dark mode or you set dark mode manually.
Is there a chance to get a fix for that?

Kind regards
Julian

**Comment by alberti42** [comment]
Dear Julian,

I am glad that you appreciate the app.

I am running Catalina and when I switch the appearance, the icon showing the "music note" on the status bar inverts its color as it should, automatically. I am surprised this is not the case for you. Do you run version 1.6.7?

Best regards,
Andrea

**Comment by julianschmidl** [comment]
Hi Andrea,
sorry for my late response. I'm unable to reproduce the issue while the computer is running. After restart (only noticed during daytime on the light theme) the icon is transparent. Switching manually to the dark theme or on automatic change the icon is visible in the correct color. 
Maybe I can try to reinstall the add-on and hope that this will fix this minor issue.
Kind regards
Julian

**Comment by alberti42** [comment]
I am not sure that reinstalling it would be of any help. Could you please be more specific what a transparent icon means? Could you send me an email with screenshots? There are perhaps better ways to detect the change of appearance between normal and dark modes, which I could implement in my app. I did not experience any problem until now, though. Therefore, I would like to make sure I understand what your problem is.

Best, Adnrea

**Comment by julianschmidl** [comment]
It's not very spectacular. The icon is just not visible (as seen in the screenshot).
But it's visible by clicking on it.

![Bildschirmfoto 2020-04-22 um 17 20 58](https://user-images.githubusercontent.com/5900943/80000793-e1c9b700-84bd-11ea-886b-1030ad802b19.png)
![Bildschirmfoto 2020-04-22 um 17 22 01](https://user-images.githubusercontent.com/5900943/80000794-e2624d80-84bd-11ea-9b0e-fd4d23e55032.png)

**Comment by alberti42** [comment]
Oh... I see... the invisible icon should be quite annoying. This does not occur on my computer. Would you like to try the version (Mojave and Catalina compatible) you find at this link https://www.icloud.com/iclouddrive/0-Xxs4_VZD8n5P2LJO1mJjqaA#iTunes_Volume_Control? I have changed the way it detects the switch of appearance and also made sure that after getting out of a sleep time, the app sets the appearance as it should.

**Comment by alberti42** [comment]
Oh... I see... the invisible icon should be quite annoying. This does not occur on my computer. Would you like to try the version (Mojave and Catalina compatible) in the the attached zip file? I have changed the way it detects the switch of appearance and also made sure that after getting out of a sleep time, the app sets the appearance as it should.Am 22.04.2020 um 17:23 schrieb julianschmidl <notifications@github.com>:It's not very spectacular. The icon is just not visible (as seen in the screenshot).
But it's visible by clicking on it.

**Comment by julianschmidl** [comment]
Fantastic! Icon is now visible after reboot and seems to change correct according to the overall appearance. Thanks for your excellent support!
