### ISSUE TITLE
Bug: interferes with accessibility / touch bar when launched for the first time 

### ISSUE THREAD

**Issue by massisenergy** [alberti42/iTunes-Volume-Control#31]
Hi, first of all, thanks for this tiny but very useful package. 

**Issue:** 
> When it is launched for the first time, the program lunches but does not work. It brings a magnified version of the touch bar on screen with dwell

![Screenshot 2020-08-30 at 15 57 51](https://user-images.githubusercontent.com/38443406/91661586-4684c600-eadd-11ea-8442-f3c95d2e8b76.jpg)

**Work-around:**
1. Launch  & enable the switch control. 
2. Switch on the 'toggle touch bar' which brings the onscreen touch bar back to the normal size.  
![Screenshot 2020-08-30 at 15 58 58](https://user-images.githubusercontent.com/38443406/91661605-60260d80-eadd-11ea-950b-0df383bac05b.jpg)
3. 'toggle touch bar' off & the volume controls works as intended, until the next re-launch.

**System**
![Screenshot 2020-08-30 at 16 05 36](https://user-images.githubusercontent.com/38443406/91661600-5b615980-eadd-11ea-9617-799b3f6ea7d4.jpg)

**Comment by alberti42** [comment]
Thank you for the feedback. This workaround must be quite annoying if you have to repeat every time. I am sorry! It is the first time that I have heard it. I would not know how to debug it unless we exchange much more information.

Are you familiar with Xcode and ObjectiveC? In case you can see what causes this anomalous behavior by downloading the source code, compiling it on your computer, and then launching the program progressing step by step or setting some breakpoint through the startup sequence of operations, to understand where it hangs.

**Comment by massisenergy** [comment]
The issue was not related to this package but something else. This problem was solved with a fresh reinstall of the MacOS 11.3.1.
