### ISSUE TITLE
Yosemite looks!

### ISSUE THREAD

**Issue by caskolkm** [alberti42/iTunes-Volume-Control#6]

**Comment by chytry** [comment]
It would be great to be able to see Yosemite volume indicator. Can't help with programming but can help with icons or graphic design related stuff.

**Comment by toonetown** [comment]
@alberti42 Even with the level of translucency and blur that you had posted in the StackOverflow question, it would still be nice to add in.  It would look at the very least, better than what it is now.

**Comment by alberti42** [comment]
Version 1.6.1 supports translucent effect just as in Mojave. You will not notice any difference.
