### ISSUE TITLE
Regression on retina resources?

### ISSUE THREAD

**Issue by eljojo** [alberti42/iTunes-Volume-Control#7]
Hi, I noticed that after updating to 1.5, I don't have the volume change doesn't have a retina icon.
The menu bar icon is retina, though.
I'm running Yosemite 10.10 (14A388a)

![screen shot 2014-11-12 at 12 08 20](https://cloud.githubusercontent.com/assets/491230/5009185/bb658b4e-6a64-11e4-9690-db4a08bfc06d.png)

**Comment by andrei4002** [comment]
Hey, first of all, nice piece of software here!

I just installed it, works fine, but I'm having the same issue discussed here (mbpro/retina)

other than that, everything seems to work as expected, good job!

**Comment by sebgiles** [comment]
Been using this program for years now, I just thought of this little improvement that you could make, I'm happy someone else has already pointed it out

**Comment by alberti42** [comment]
Glad to hear that.. if I had the time, I would like to add the control of Spotify as well. I need to correct a few bugs, but it is already working on my comptuer.

Best regards,
Andrea

----
IAP - Institut für Angewandte Physik
Wegelerstr. 8 - 53115 Bonn - Germany
Tel: +49 228 73-3471 Fax: +49 228 73-3474
email: alberti@iap.uni-bonn.de <mailto:alberti@iap.uni-bonn.de>
www: http://quantum-technologies.iap.uni-bonn.de/alberti <http://quantum-technologies.iap.uni-bonn.de/alberti/>

**Comment by deadlyknapsack** [comment]
Hi alberti42,

I have the latest version installed, but still I see the low resolution images like eljoj pointed out. Could you send me high resolution tiff images as well? I could easily replace them myself.

With regards,

DK

**Comment by deadlyknapsack** [comment]
@eljojo 

So, let me get this straight, you close this topic, although I still have a question open? What a way to support this community... how about you share the retina graphics with me directly? deadlyknapsack at gmail.com. Thanks.

**Comment by eljojo** [comment]
Lol you're seriously giving me shit for closing an issue about a problem
I literally had in 2014?
Not supporting this community? Mate I'm the one who reported the bug in
the first place.
The author is clearly not doing something about this, which is fine.
This is not an issue to me anymore, and no, I don't have the icons. 

@alberti42 could you lock the issue?

On Thu, May 4, 2017, at 03:06 AM, deadlyknapsack wrote:
> @eljojo[1]


> So, let me get this straight, you close this topic, although I still
> have a question open? What a way to support this community... how
> about you share the retina graphics with me directly? deadlyknapsack
> at gmail.com. Thanks.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 

Links:

  1. https://github.com/eljojo
  2. https://github.com/alberti42/iTunes-Volume-Control/issues/7#issuecomment-299111371

**Comment by alberti42** [comment]
I am the author. I will look into this on the weekend. I agree that I should provide support if this does not cost me too much time. In the last two years I had very little free time.

----
Andrea Alberti, PhD
IAP - Institut für Angewandte Physik, Universität Bonn
Wegelerstr. 8 - 53115 Bonn - Germany
Tel: +49 228 73-3471 Fax: +49 228 73-3474
email: alberti@iap.uni-bonn.de <mailto:alberti@iap.uni-bonn.de>
www: http://quantum-technologies.iap.uni-bonn.de/alberti/ <http://quantum-technologies.iap.uni-bonn.de/alberti/>

**Comment by deadlyknapsack** [comment]
@alberti42 Hi. Did you get a chance to look at this? You can just send me the high resolution images, I will replace them myself.
