### ISSUE TITLE
Controlling Spotify 

### ISSUE THREAD

**Issue by chytry** [alberti42/iTunes-Volume-Control#8]
Thank you for great plugin. It would be great to control Spotify volume too. 

Cheers

**Comment by alberti42** [comment]
Actually the development version can already do it. I only need a bit of time to release it and finish testing it.

Best,
Andrea

----
IAP - Institut für Angewandte Physik
Wegelerstr. 8 - 53115 Bonn - Germany
Tel: +49 228 73-3471 Fax: +49 228 73-3474
email: alberti@iap.uni-bonn.de <mailto:alberti@iap.uni-bonn.de>
www: http://quantum-technologies.iap.uni-bonn.de/alberti <http://quantum-technologies.iap.uni-bonn.de/alberti/>

**Comment by chytry** [comment]
Beautiful! Can i help with tests?

**Comment by normanmaurer** [comment]
@alberti42 any update here ? If not can you add some docs how to compile...

**Comment by normanmaurer** [comment]
Nevermind just build it via Xcode and it works great so far :)

**Comment by alberti42** [comment]
This feature is now available in version 1.6.0.

**Comment by alberti42** [comment]
This feature is now available in version 1.6.0.
