### ISSUE TITLE
Native Like Volume Step [Suggestion]

### ISSUE THREAD

**Issue by kristianvld** [alberti42/iTunes-Volume-Control#9]
First of all, that you very much for this application. It is exactly what I have been looking for works like a charm. The only thing that I find a bit odd is the volume step. You can set it and so on, but none of the percentage options hits the 16 square dots perfectly. Native volume control just goes one dot at a time, but if you in addition hold the SHIFT button then it goes 1/3 of a square. Feel something like this would be a more natural and stimulate my OCD a little bit ;)

See that it is quite a while since last commit/issue report, but still hope that this would be implemented.

**Comment by alberti42** [comment]
Dear kristianvld,

It was long time that I did not touch this application. I have now implemented a native control of volume for Mojave. I will soon upload a newer version where also finer steps are possible after your suggestion. I am planning in the future to add support for Spotify as well and some other improvements.

Best,
Andrea

**Comment by alberti42** [comment]
A native control of volume as you suggested is now available in v1.6.1.

**Comment by kristianvld** [comment]
Daym, old issue but a welcome update. Still use this basically everyday 👌

**Comment by alberti42** [comment]
Thanks for the feedback. I am glad that other than me finds this useful.
